version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports: 
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root 
      - MONGO_INITDB_ROOT_PASSWORD=akshansh1998
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports: 
      - 8081:8081
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=akshansh1998
      - ME_CONFIG_MONGODB_SERVER=mongodb

  
